@startuml
title master-slave-copy

rectangle "redis\n[master]" as master #red
rectangle "redis\n[slave]" as slave #red

slave -left-> master: 复制
@enduml

@startuml
title master-many-slave

rectangle "redis\n[master]" as master #red
rectangle "redis\n[slave]" as slaveA #red
rectangle "redis\n[slave]" as slaveB #red
rectangle "redis\n[slave]" as slaveC #red

slaveA -down-> master: 复制
slaveB -left-> master: 复制
slaveC -up-> master: 复制
@enduml

@startuml
title slave-of
skinparam style strictuml

rectangle "客户端" as client #lightpink
rectangle "redis\nslave\n127.0.0.1:6380" as slave #red
rectangle "redis\nmaster\n127.0.0.1:6379" as master #red

client -right-> slave: slaveof
slave -left-> client: OK(异步)
slave -right-> master: 复制
@enduml

@startuml
title slave-of-no-one
skinparam style strictuml

rectangle "客户端" as client #lightpink
rectangle "redis\nslave\n127.0.0.1:6380" as slave #red
rectangle "redis\nmaster\n127.0.0.1:6379" as master #red

client -right-> slave: slaveof no one
slave -left-> client: OK
slave -right-> master: ×
@enduml

@startuml
title full-copy
skinparam style strictuml

participant "redis slave" as slave #red
participant "redis master" as master #red

autonumber
slave -> master: psync ? -1
master -> slave: +FULLRESYNC\n{runId} {offset}
slave -> slave: save masterInfo
master -> master: bgsave
master -> slave: send RDB
master -> slave: send buffer
slave -> slave: flush old data
slave -> slave: load RDB
slave -> slave: 如果开启aof，bgrewriteaof
@enduml